name: [Health Metrics] Release Diffing

on:
  push:
    tags: ['**']

jobs:
  tags-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - uses: yifanyang/github-actions/health-metrics/release-diffing@master
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          commit: ${{ github.sha }}
